package Exercise20_22;

import java.util.Scanner;
import java.util.Stack;

//this was generated by AI
public class App {
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        System.out.print("Enter number of disks: ");
        int n = input.nextInt();

        System.out.println("The moves are:");
        moveDisks(n, 'A', 'B', 'C');
    }

    public static void moveDisks(int n, char fromTower, char toTower, char auxTower) {
        Stack<int[]> stack = new Stack<>();
        stack.push(new int[]{n, fromTower, toTower, auxTower});

        while (!stack.isEmpty()) {
            int[] move = stack.pop();
            int disks = move[0];
            char from = (char) move[1];
            char to = (char) move[2];
            char aux = (char) move[3];

            if (disks == 1) {
                System.out.println("Move disk 1 from " + from + " to " + to);
            } else {
                // Push in reverse order (LIFO)
                stack.push(new int[]{disks - 1, aux, to, from});
                stack.push(new int[]{1, from, to, aux});
                stack.push(new int[]{disks - 1, from, aux, to});
            }
        }
    }
}
