package Exercise10_8;

// This class was generated by AI
public class App {
    public static void main(String[] args) {
        // 2001 tax rates
        double[] rates2001 = {0.15, 0.275, 0.305, 0.355, 0.391};
        int[][] brackets2001 = {
                {27050, 65550, 136750, 297350},  // Single
                {45200, 109250, 166500, 297350}, // Married Joint
                {22600, 54625, 83250, 148675},   // Married Separate
                {36250, 93650, 151650, 297350}   // Head of Household
        };

        // 2009 tax rates
        double[] rates2009 = {0.10, 0.15, 0.25, 0.28, 0.33, 0.35};
        int[][] brackets2009 = {
                {8350, 33950, 82250, 171550, 372950},  // Single
                {16700, 67900, 137050, 208850, 372950}, // Married Joint
                {8350, 33950, 68525, 104425, 186475},   // Married Separate
                {11950, 45500, 117450, 190200, 372950}  // Head of Household
        };

        String[] statusNames = {"Single Filer", "Married Jointly", "Married Separately", "Head of Household"};

        System.out.println("=== 2001 Tax Table ===");
        for (int status = 0; status < 4; status++) {
            System.out.println("\n" + statusNames[status]);
            System.out.println("Income\tTax");
            Tax tax = new Tax(status, brackets2001, rates2001, 0);

            for (int income = 50000; income <= 60000; income += 1000) {
                tax.setTaxableIncome(income);
                System.out.printf("%d\t%.2f\n", income, tax.getTax());
            }
        }

        System.out.println("\n=== 2009 Tax Table ===");
        for (int status = 0; status < 4; status++) {
            System.out.println("\n" + statusNames[status]);
            System.out.println("Income\tTax");
            Tax tax = new Tax(status, brackets2009, rates2009, 0);

            for (int income = 50000; income <= 60000; income += 1000) {
                tax.setTaxableIncome(income);
                System.out.printf("%d\t%.2f\n", income, tax.getTax());
            }
        }
    }
}
